//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsaacLauncherGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsaacLauncherGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon beast {
            get {
                object obj = ResourceManager.GetObject("beast", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steam_api {
            get {
                object obj = ResourceManager.GetObject("steam_api", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEAMAPPS_INTERFACE_VERSION008
        ///SteamClient017
        ///SteamController008
        ///SteamFriends017
        ///SteamGameServerStats001
        ///SteamGameServer015
        ///STEAMHTMLSURFACE_INTERFACE_VERSION_005
        ///STEAMHTTP_INTERFACE_VERSION003
        ///SteamInput006
        ///STEAMINVENTORY_INTERFACE_V003
        ///SteamMatchMakingServers002
        ///SteamMatchMaking009
        ///SteamMatchGameSearch001
        ///SteamParties002
        ///STEAMMUSIC_INTERFACE_VERSION001
        ///STEAMMUSICREMOTE_INTERFACE_VERSION001
        ///SteamNetworkingMessages002
        ///SteamNetworkingSockets012
        ///SteamNetworkingUtils004
        ///SteamNetworking006
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steam_interfaces {
            get {
                return ResourceManager.GetString("steam_interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steamless {
            get {
                object obj = ResourceManager.GetObject("steamless", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
